### ISSUE TITLE
Reservaties worden in loop gecleared

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#16]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/ReservationTimer.java#L54

Op deze manier wordt de loop een beetje overbodig, klopt wat hier staat?

**Comment by yorick3** [comment]
Bug is gefixt
