### ISSUE TITLE
Harde exception

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#17]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/Server.java#L39

Deze lijn moet de hele applicatie laten stoppen.

**Comment by yorick3** [comment]
Applicatie exit nu (met code 1) wanneer de properties niet gevonden worden
