### ISSUE TITLE
Reservations are not cleared

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#2]
You keep adding reservations to a list, even the already present ones. 
Don't forget to clear the list first :).

https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/9629c4b26b37f79a03a80c19be54fd981979f24f/src/main/java/Communication/server/ReservationTimer.java#L54

**Comment by yorick3** [comment]
Issue fixed in commit e2a70e94af21aafe21fc07b07a9183e7ced379d9, thanks for the heads-up ;)
