### ISSUE TITLE
Verschillende taken in class

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#20]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/Server.java#L29

We moeten de timers, installeren van ruimtes etc misschien overlaten aan een boot meganisme.

**Comment by yorick3** [comment]
Server klasse overzichtelijker gemaakt en eigen methodes voor instellingen gemaakt
