### ISSUE TITLE
Time wordt niet geupdate

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#21]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/UtilTimerTask.java#L18

Je vergeet time te zetten naar het nieuwe tijdstip. 
voor de rest moeten je misschien aan de calendar resource vragen voor een geupdate dump.

**Comment by carlo-theunissen** [comment]
De calendar resource veranderd vanaf nu automatisch de collecties met reserveringen. Ook bij het veranderen van de dag. Zodoende is de UntilTimerTask niet meer nodig.

Kan je die geheel verwijderen?

**Comment by yorick3** [comment]
UtilTimerTask en usages hiervan zijn verwijderd uit de code.
