### ISSUE TITLE
Sluit connectie

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#22]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/WebSocket.java#L64

Het is netter als je een errormelding naar de client stuurt en dan de websocket connectie verbreekt.

**Comment by yorick3** [comment]
Code hierop aangepast
