### ISSUE TITLE
Onnodige code

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#24]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/WebSocket.java#L58

Deze code doet niks. Toch?

**Comment by yorick3** [comment]
Klopt, code weggehaald en de rest van de klasse hierop aangepast.
