### ISSUE TITLE
Broadcast ipv send

### ISSUE THREAD

**Issue by carlo-theunissen** [Meeting-App-ISAAC/MeetingRoom-Backend#25]
https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend/blob/42c5d87acaa387103aca4a4a9887da1641e5327a/src/main/java/Communication/server/WebSocket.java#L59

Je broadcast een dump naar alle clients. Je hoort toch eigenlijk de dump alleen naar de nieuwe client te sturen?

**Comment by yorick3** [comment]
sendReservationDump gebruikt de sendTo methode om de dump ook alleen naar de nieuwe client te sturen. Er word dus niets gebroadcast.
